version: '3.4'
 
networks:
    practices:    
        driver: bridge  
 
services:
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        restart: always
        ports:
            - 6474:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=marioalbertodaniel
        networks:
            - cryptoapp
        volumes:
            - db-data:/var/opt/mssql
    api:
        restart: unless-stopped 
        ports:
            - 4746:80 
        build:
          context: .
          dockerfile: API/Dockerfile
        depends_on:
            - db
        networks:
            - practices
